#!/usr/bin/env python3
"""Write a minimal JDK fontconfig.properties for the native binary.

A GraalVM native image does not carry the fontconfig data the JVM uses, so
Java2D fails with "Fontconfig head is null" the first time it measures text.
Pointing sun.awt.fontconfig at a properties file fixes that. This script finds
the DejaVu families on the machine and writes the file next to the executable.

Usage:
    python3 tools/generate-fontconfig.py build/native/fontconfig.properties
"""

import sys
from pathlib import Path

FONT_DIRS = [
    Path("/usr/share/fonts"),
    Path("/usr/local/share/fonts"),
    Path.home() / ".local/share/fonts",
    Path.home() / ".fonts",
]

STYLE_SUFFIXES = ["", " Bold", " Oblique", " Bold Oblique"]

# Family label -> file name per style suffix.
FAMILIES = {
    "DejaVu Sans": {
        "": "DejaVuSans.ttf",
        " Bold": "DejaVuSans-Bold.ttf",
        " Oblique": "DejaVuSans-Oblique.ttf",
        " Bold Oblique": "DejaVuSans-BoldOblique.ttf",
    },
    "DejaVu Serif": {
        "": "DejaVuSerif.ttf",
        " Bold": "DejaVuSerif-Bold.ttf",
        " Oblique": "DejaVuSerif-Italic.ttf",
        " Bold Oblique": "DejaVuSerif-BoldItalic.ttf",
    },
    "DejaVu Sans Mono": {
        "": "DejaVuSansMono.ttf",
        " Bold": "DejaVuSansMono-Bold.ttf",
        " Oblique": "DejaVuSansMono-Oblique.ttf",
        " Bold Oblique": "DejaVuSansMono-BoldOblique.ttf",
    },
}

# Logical font -> preferred family, falling back to the first complete family.
LOGICAL = {
    "dialog": "DejaVu Sans",
    "sansserif": "DejaVu Sans",
    "serif": "DejaVu Serif",
    "monospaced": "DejaVu Sans Mono",
}


def locate(file_name):
    for root in FONT_DIRS:
        if not root.is_dir():
            continue
        matches = sorted(root.rglob(file_name))
        if matches:
            return matches[0]
    return None


def main():
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    target = Path(sys.argv[1])

    complete = {}
    for family, variants in FAMILIES.items():
        paths = {}
        for suffix, file_name in variants.items():
            found = locate(file_name)
            if found is not None:
                paths[suffix] = found
        if len(paths) == len(STYLE_SUFFIXES):
            complete[family] = paths

    if not complete:
        print("no complete DejaVu family found; no fontconfig.properties written")
        return 0

    fallback = next(iter(complete))
    lines = [
        "# Generated by tools/generate-fontconfig.py for the GraalVM native image.",
        "# Java2D reads this through -Dsun.awt.fontconfig.",
        "version=1",
        "",
    ]
    for logical, preferred in LOGICAL.items():
        family = preferred if preferred in complete else fallback
        for suffix in STYLE_SUFFIXES:
            style = {"": "plain", " Bold": "bold", " Oblique": "italic",
                     " Bold Oblique": "bolditalic"}[suffix]
            lines.append(f"{logical}.{style}.latin-1={family}{suffix}")
    lines.append("")
    lines.append("sequence.allfonts=latin-1")
    lines.append("")
    for family, paths in complete.items():
        for suffix, path in paths.items():
            key = (family + suffix).replace(" ", "_")
            lines.append(f"filename.{key}={path}")
    lines.append("")

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {target} with {len(complete)} families")
    return 0


if __name__ == "__main__":
    sys.exit(main())
